services:
  mariadb:
    image: mariadb:11.4
    container_name: mariadb_trading
    environment:
      MARIADB_ROOT_PASSWORD: rootpass
    ports:
      - "43306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./docker/mariadb/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "mariadb-admin ping -prootpass --silent"]
      interval: 5s
      timeout: 3s
      retries: 30
      start_period: 10s




volumes:
  mariadb_data: